### ISSUE TITLE
identities clarification

### ISSUE THREAD

**Issue by Diozao666** [rpolicastro/scProportionTest#1]
Hello
You replied to my thread on biostars a while ago, which I thank you again. I have been trying to run the code but got a few issues

I assumed that if my seurat object is already loaded this step is not necessary, is this correct?
```
seurat_data <- system.file("extdata", "example_data.RDS", package = "scProportionTest")
seurat_data <- readRDS(seurat_data)
```
I'm not a R expert but it seems a bit strange to create the first line as it would be replaced by the second. So I just ran this line, with "seurat_data" as my seurat object.

`prop_test <- sc_utils(seurat_data)`

This last step

```
prop_test <- permutation_test(
	prop_test, cluster_identity = "custom_clusters",
	sample_1 = "HT29_EV", sample_2 = "HT29_LSD1_KD",
	sample_identity = "orig.ident"
)
```

Gave me this error

```
Error in dcast.data.table(obs_diff, clusters ~ samples, value.var = "fraction") : 
  Can not cast an empty data.table
```

Also, if I understood it correctly this should find differences in the proportion in a custom cluster between another identity class, normalized by the number of samples that belong to said identity class, using three identities:

1. the cluster
2. the treatment or condition
3. the sample

However, apparently I can input only 2 samples, and orig.ident relates to the cell labels, so I am very confused

**Comment by rpolicastro** [comment]
Hi,

> I assumed that if my seurat object is already loaded this step is not necessary, is this correct?

That is correct. Those lines are to load up example data so you can test running through the vignette.

As for the last step, let me explain in more detail what each argument in the function entails. `cluster_identity` should be the column in your seurat metadata that contains the factor levels for each cell that you want to test for differences in proportions. These can be clusters, cell cycle phase, etc. `sample_identity` is the name of the column in your metadata that has the sample type for each cell, such as treatment or condition. Finally, `sample_1` and `sample_2` should be the two conditions/treatments you want to compare within the column defined by `sample_identity`.

If you want more specific advice feel free to include the first few lines of your meta data with `head(seurat_data[[]])`.

**Comment by Diozao666** [comment]
Thanks for the support!
I still have to load some meta.data 
In my case I have more than one "treatment" (it is 3 different COVID-19 severities, one severe FLU cohort and healthy controls). I would like to see if a cell cluster is more representative in one condition than another. In this case, would it be advisable to repeat the process using all combinations?

**Comment by rpolicastro** [comment]
> In this case, would it be advisable to repeat the process using all combinations?

Yep, you can make a loop to iterate over all the combinations you care about. As long as all the samples are in one seurat object, and there is a metadata column with sample identity, you shouldn't run into any problems.

**Comment by Diozao666** [comment]
Everything seems to have worked perfectly! Thanks! I would only like to confirm if I did this correctly

This is my data

```
> head(flucov.integrated.CD4[[]])
                   orig.ident nCount_RNA nFeature_RNA Sample      Status percent.mt integrated_snn_res.0.5
AAACCCAGTCTTCGAA-1     flucov       6796         1785      1 nCoV-Severe   3.546204                      1
AAAGAACCACACGTGC-1     flucov      10904         2159      1 nCoV-Severe   5.181585                      5
AAAGAACCAGTTAAAG-1     flucov      10545         2014      1 nCoV-Severe   2.655287                      5
AAAGGATCAAGACAAT-1     flucov       6165         1569      1 nCoV-Severe   8.321168                      1
AAAGGGCAGAGCTTTC-1     flucov       8392         1754      1 nCoV-Severe   5.695901                      2
AAAGTGAGTTTCGTAG-1     flucov       6008         1769      1 nCoV-Severe   7.073901                      9
                   seurat_clusters integrated_snn_res.0.3 integrated_snn_res.0.2 integrated_snn_res.0.8
AAACCCAGTCTTCGAA-1               1                      1                      5                      1
AAAGAACCACACGTGC-1               4                      1                      5                      4
AAAGAACCAGTTAAAG-1               4                      1                      5                      4
AAAGGATCAAGACAAT-1               1                      1                      5                      1
AAAGGGCAGAGCTTTC-1               2                      0                      5                      2
AAAGTGAGTTTCGTAG-1              10                      2                      5                      9
                   integrated_snn_res.1 integrated_snn_res.0.9     S.Score    G2M.Score Phase old.ident
AAACCCAGTCTTCGAA-1                    4                      1 -0.02760033 -0.012573486    G1         1
AAAGAACCACACGTGC-1                    4                      4  0.05941819 -0.029188525     S         4
AAAGAACCAGTTAAAG-1                    4                      4  0.05565022 -0.002421625     S         4
AAAGGATCAAGACAAT-1                    4                      1 -0.04221643 -0.065137555    G1         1
AAAGGGCAGAGCTTTC-1                    7                      2 -0.02348025 -0.068009500    G1         2
AAAGTGAGTTTCGTAG-1                    4                     10 -0.02319227  0.006871107   G2M        10

```
This is how I wrote the code

```
prop_test <- sc_utils(flucov.integrated.CD4)
prop_test <- permutation_test(
  prop_test, cluster_identity = "integrated_snn_res.0.9",
  sample_1 = "Normal", sample_2 = "nCoV-Mild",
  sample_identity = "Status"
)

permutation_plot(prop_test)
```

However, I have a different number of donors for each condition (in the "Sample" column) but from what I understood this information is not taken into account in the code, so would any error that might arise from this be taken care of in the statistical test?

**Comment by rpolicastro** [comment]
If the patient samples of each type are similar, the test will be robust to sample sizes.
