### ISSUE TITLE
no slot of name "meta_data"

### ISSUE THREAD

**Issue by Oakento** [rpolicastro/scProportionTest#10]
unable to run permutation_test with Seurat 4.1.0 object. Getting error of 
```
Error in copy(sc_utils_obj@meta_data) : 
  no slot of name "meta_data" for this object of class "Seurat"
```
the current seurat uses `meta.data` as the metadata slot

**Comment by rpolicastro** [comment]
Hello,

What code are you running? It should generally be in the form of:

```
prop_object <- sc_utils(seurat_object)
test_results <- permutation_test(prop_object, ...)
```

You might be trying to pass the Seurat object into the `permutation_test` function.

Cheers,
Bob

**Comment by Oakento** [comment]
> Hello,
> 
> What code are you running? It should generally be in the form of:
> 
> ```
> prop_object <- sc_utils(seurat_object)
> test_results <- permutation_test(prop_object, ...)
> ```
> 
> You might be trying to pass the Seurat object into the `permutation_test` function.
> 
> Cheers, Bob

Thanks for pointing this out for me. I missed the `sc_utils` part. After transforming seurat object by `sc_utils` it works well. 

Best,
kento
