### ISSUE TITLE
multiple samples

### ISSUE THREAD

**Issue by hchintalapudi** [rpolicastro/scProportionTest#2]
Hi,
Thank you for the useful tool, it is pretty neat!
What's your advice on doing similar analysis for two different samples when they are not integrated and have different number of clusters?

Thanks.

**Comment by rpolicastro** [comment]
Hi hchintalapudi,

The clusters should have the same name between the two samples. More importantly, you want to make sure that, for example, one cluster/cell type isn't being uninformatively split into multiple clusters in one sample compared to another. If those conditions are met any missing clusters will just return a value of infinity, so those cells will still factor into the calculation but shouldn't cause a problem.
