### ISSUE TITLE
Question on replicates

### ISSUE THREAD

**Issue by jhb1980** [rpolicastro/scProportionTest#3]
Hello! 
Thank you very much for an important tool in single cell (and flow 😉) analysis!
I was wondering what your thoughts are on integrating this information? I think at the moment, your test statistic bis based on the pool of replicates if available?

**Comment by rpolicastro** [comment]
Hi!

If your biological replicates appear similar, you can pool the replicates into one larger sample and compare those. This applies to technical replicates as well.

Cheers,
Bob

**Comment by kaizen89** [comment]
Hi @rpolicastro, I have a question regarding biological replicates with different sample sizes. I have two groups (A and B) and several samples for each condition, let's 6 samples for group A and 15 for B. If I want to compare the proportion of a cluster in group A vs B, do I have to downsample the number of cells such that #cells group A is close enough to #cells condition B? Thanks!
